services:
  hugo:
    build:
      context: .
      args:
        HUGO_VERSION: "0.158.0"
    ports:
      - "1313:1313"
    volumes:
      - .:/site
    command:
      - server
      - -D
      - --bind
      - 0.0.0.0
      - --baseURL
      - http://localhost:1313
